@startuml realizacao_pedido

actor "Atendente" as Atendente

boundary "Interface Emprestimo" as Interface

control "Sistema Biblioteca" as Controller

entity "Usuario" as Usuario
entity "Livro" as Livro
entity "Emprestimo" as Emprestimo

database "Banco de Dados" as Banco

Atendente -> Interface: solicitarEmprestimo(Usuario, livro)

Interface -> Controller: realizarEmprestimo(Usuario, Livro)

activate Controller
Controller -> Usuario: verificarSituacao()

activate Usuario
Usuario --> Controller: usuarioApto
deactivate Usuario

Controller -> Livro: verificarDisponibilidade()

activate Livro
Livro --> Controller : livroDisponivel
deactivate Livro

alt Usuario apto & Livro disponivel
  Controller -> Emprestimo : criar(Usuario, Livro)
  
  activate Emprestimo
  Emprestimo --> Controller : emprestimoCriado
  deactivate Emprestimo
  
  Controller -> Banco : salvar(Emprestimo)
  
  activate Banco
  Banco --> Controller : emprestimo salvo
  deactivate Banco
  
  Controller -> Livro : atualizarStatus("emprestado") 
  
  activate Livro
  Livro --> Controller : statusAtualizado 
  deactivate Livro
  
  Controller --> Interface : confirmarEmprestimo()
  
  Interface --> Atendente : exibirConfirmação()
else Usuario nao apto & Livro indisponivel
  Controller --> Interface : informarErro()
  Interface --> Atendente : exibirMenssagemErro()
end

deactivate Controller

@enduml